### ISSUE TITLE
Module youtube

### ISSUE THREAD

**Issue by justmemaarten** [renatokuipers/TikTok-Puller-with-audio#1]
Welke module moet ik precies installeren voor de volgende error:

python3 main.py
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from youtube import Video
ModuleNotFoundError: No module named 'youtube'

Als ik deze uitschakel krijg ik het volgende
 python3 main.py
Het script staat op github.com/renatokuipers
Dit is een project die ik maak puur uit hobby.
Chats komen in het scherm te staan.
Follow, Share of Gift voor soundeffects.
Typ /help voor commando's

maar dit sluit ver volgends ook meteen af

**Comment by renatokuipers** [comment]
Dan moet je "pip install youtube" installeren als het goed is.

**Comment by justmemaarten** [comment]
Youtube module bestaat niet helaas :/

**Comment by renatokuipers** [comment]
pip install pytube en 
pip install youtubesearchpython 
Zijn voorbeelden die ook gebruikt worden

In principe alles wat "import" of "from" is, kan via "pip install" gedaan worden. Echter sommige zijn standaard binnen python.

Sorry voor het misschien onduidelijke antwoord, maar ik heb het via de telefoon beantwoord
